# Generated by Django 5.0.6 on 2024-08-06 09:47

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.IntegerField(choices=[(1, 'Landscape'), (2, 'Portrait'), (3, 'Wildlife'), (4, 'Street'), (5, 'Macro')], unique=True)),
                ('image', models.ImageField(upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('categoryimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.category')),
            ],
        ),
    ]
