# Generated by Django 5.0.6 on 2024-07-30 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait'), ('Wildlife', 'Wildlife'), ('Street', 'Street'), ('Macro', 'Macro')], default='Landscape', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait'), ('Wildlife', 'Wildlife'), ('Street', 'Street'), ('Macro', 'Macro')], default='Landscape', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
