# Generated by Django 5.0.6 on 2024-06-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='blog', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
