# Generated by Django 5.0.6 on 2024-07-27 17:11

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_landscapeimage_post_created_at_post_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandscapeImage',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(default=datetime.datetime(2024, 7, 27, 17, 10, 57, 325100, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
